FlaskApp/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Post")

FlaskApp/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from FlaskApp import db
from FlaskApp.database import Post
from FlaskApp.posts.forms import PostForm

posts = Blueprint("posts", __name__)

@posts.route("/create_post", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Ur post posted", "success")
        return redirect(url_for("main.home"))
    return render_template("create_post.html", form=form, legend="New post")

@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", post=post)

@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("ur post updated")
        return redirect(url_for("posts.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template("create_post.html", form=form, legend="Update post")

@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("deleted yay!")
    return redirect(url_for('main.home'))

FlaskApp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from FlaskApp import db, bcrypt
from FlaskApp.database import User, Post
from FlaskApp.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from FlaskApp.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()   
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for { form.username.data }!", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", form = form)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()    
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else  redirect(url_for("main.home"))
        else:
            flash("Log in unsuccessfull.", "danger")
    return render_template("login.html", form = form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("your account has been updated", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename="profile_pic" + current_user.image_file)
    return render_template("account.html", image_file=image_file, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=2)
    return render_template("user_posts.html", posts=posts, user=user)

@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent to reset your password.", "info")
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", form=form)

@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That was an invalid or expired token.", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user.password = hashed_password
        db.session.commit()
        flash(f"Password is updated!!", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html",form=form)

FlaskApp/templates/account.html
{% extends "layout.html" %}

{% block content %}
<h1>ur name</h1>
<img src="{{ image_file }}">
<div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>account Info</legend>
            <div>
                {{ form.username.label() }}

                {% if form.username.errors %}
                    {{ form.username() }}
                    <div>
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username() }}
                {% endif %}
            </div>   
            <div>
                {{ form.email.label() }}
                {% if form.email.errors %}
                    {{ form.email() }}
                    <div>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email() }}
                {% endif %}
            </div>        
            <div>
                {{ form.picture.label() }}
                {{ form.picture() }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div>
            {{ form.submit() }}
        </div>
    </form>
</div>
{% endblock %}

FlaskApp/templates/create_post.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend> {{ legend }} </legend>            
            <div>
                {{ form.title.label() }}
                {% if form.title.errors %}
                    {{ form.title() }}
                    <div>
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title() }}
                {% endif %}
            </div>        
            <div>
                {{ form.content.label() }}
                {% if form.content.errors %}
                    {{ form.content() }}
                    <div>
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content() }}
                {% endif %}
            </div>
        </fieldset>
        <div>
            {{ form.submit() }}
        </div>
    </form>
</div>
{% endblock %}

FlaskApp/templates/home.html
{% extends "layout.html" %}

{% block content %}
{% for post in posts.items %}
    <div>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <a href= " {{ url_for('posts.post', post_id=post.id) }} " >{{ post.title }}</a>
        {{ post.content }}
    </div>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        <a href="{{ url_for('main.home', page=page_num) }}">{{page_num}}</a>
    {% else %}
        ...
    {% endif %}
{% endfor %}
{% endblock %}

FlaskApp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <div>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('users.logout') }}">Log out</a>
                <a href="{{ url_for('users.account') }}">account</a>
                <a href="{{ url_for('posts.new_post') }}">Create post!</a>
            {% else %}
                <a href="{{ url_for('users.register') }}">register</a>
                <a href="{{ url_for('users.login') }}">Login</a>
            {% endif %}
        </div>
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ messages }}
                    </div>
                {% endfor %}
            {% endif %}  
        {% endwith %}    
    </header>        
    {% block content %}
    {% endblock %}
</body>
</html>

FlaskApp/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Log In</legend>
            
            <div>
                {{ form.email.label() }}
                {% if form.email.errors %}
                    {{ form.email() }}
                    <div>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email() }}
                {% endif %}
            </div>        
            <div>
                {{ form.password.label() }}
                {% if form.password.errors %}
                    {{ form.password() }}
                    <div>
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password() }}
                {% endif %}
            </div>
            <div>
                {{ form.remember() }}
                {{ form.remember.label() }}
            </div>
        </fieldset>
        <div>
            {{ form.submit() }}
        </div>
        <small><a href=" {{url_for('users.reset_request')}} ">forgot password?</a></small>
    </form>
</div>
<small>
    Need to exist? <a href="register">E X I S T</a>.
</small>
{% endblock %}

FlaskApp/templates/post.html
{% extends "layout.html" %}

{% block content %}

<div>
    <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
    {{ post.title }}
    {{ post.content }}
    {% if post.author == current_user %}
        <div>
            <a href="{{ url_for('posts.update_post', post_id=post.id)}}">Update post</a>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
        </div>
    {% endif %}
</div>

{% endblock %}

FlaskApp/templates/register.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Join Today!</legend>
            <div>
                {{ form.username.label() }}

                {% if form.username.errors %}
                    {{ form.username() }}
                    <div>
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username() }}
                {% endif %}
            </div>   
            <div>
                {{ form.email.label() }}
                {% if form.email.errors %}
                    {{ form.email() }}
                    <div>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email() }}
                {% endif %}
            </div>        
            <div>
                {{ form.password.label() }}
                {% if form.password.errors %}
                    {{ form.password() }}
                    <div>
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password() }}
                {% endif %}
            </div>
            <div>confirm_password
                {{ form.confirm_password.label() }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password() }}
                    <div>
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password() }}
                {% endif %}
            </div>
        </fieldset>
        <div>
            {{ form.submit() }}
        </div>
    </form>
</div>
<small>
    Already exist? <a href="login">log in</a>.
</small>
{% endblock %}

FlaskApp/templates/reset_request.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Reset Password</legend>
            <div>
                {{ form.email.label() }}
                {% if form.email.errors %}
                    {{ form.email() }}
                    <div>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email() }}
                {% endif %}
            </div>        
        </fieldset>
        <div>
            {{ form.submit() }}
        </div>
    </form>
</div>

{% endblock %}

FlaskApp/templates/reset_token.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Reset Password</legend>
            <div>
                {{ form.password.label() }}
                {% if form.password.errors %}
                    {{ form.password() }}
                    <div>
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password() }}
                {% endif %}
            </div> 
            <div>
                {{ form.confirm_password.label() }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password() }}
                    <div>
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password() }}
                {% endif %}
            </div>        
        </fieldset>
        <div>
            {{ form.submit() }}
        </div>
    </form>
</div>

{% endblock %}

FlaskApp/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}
<h1 class=>Posts by {{user.username}} </h1>
{% for post in posts.items %}
    <div>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <a href= " {{ url_for('posts.post', post_id=post.id) }} " >{{ post.title }}</a>
        {{ post.content }}
    </div>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        <a href="{{ url_for('users.user_posts',username=user.username, page=page_num) }}">{{page_num}}</a>
    {% else %}
        ...
    {% endif %}
{% endfor %}
{% endblock %}